### ISSUE TITLE
Add an event for the DKG plenary meeting in Budapest

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [KNowledgeOnWebScale/cost-dkg-website#1]
The DKG meeting on Oct. 2022 is not listed in the list of events.

**Comment by pheyvaer** [comment]
Hi @Antoine-Zimmermann do you have the details of this event?

**Comment by kaefer3000** [comment]
GP2 Plenary Meeting
on Oct 13+14, 2022
at SZTAKI https://www.sztaki.hu/ in Budapest, Hungary
