### ISSUE TITLE
new virtual talk

### ISSUE THREAD

**Issue by andimou** [KNowledgeOnWebScale/cost-dkg-website#21]
Could we add a new event similar to "[On the broad applicability of Semantic Web technologies](https://cost-dkg.eu/talks) (Tue, Dec 7th 2021 6PM (MST))" where Ian Horrocks would give a virtual talk on May 17th at 18.00?

The title and abstract will be share by end of March.

Thank you!

**Comment by pheyvaer** [comment]
Hi @andimou, should I already add the talk or do you want me to wait till you have the abstract and title?

**Comment by andimou** [comment]
go ahead with the announcement of the dates so we can start the publicity and once we have the title and the abstract, we can add them.
