### ISSUE TITLE
Add related event

### ISSUE THREAD

**Issue by andimou** [KNowledgeOnWebScale/cost-dkg-website#5]
There was this related event: https://www.wu.ac.at/en/dpkm/news-details/detail/guest-talk-frank-van-harmelen-hybrid-intelligence-ai-systems-that-collaborate-with-people-instead-of-replacing-them/ 

which has a recording of Frank's presentation. 
We would like to have it advertised via our website. @pheyvaer Would it be possible to add please?

Thank you in advance!

**Comment by pheyvaer** [comment]
@andimou What do you mean with advertise? Add it to the events page?

**Comment by andimou** [comment]
yes add it as an event so people who land on this website, they can see it
