### ISSUE TITLE
GP3 events

### ISSUE THREAD

**Issue by kaefer3000** [KNowledgeOnWebScale/cost-dkg-website#9]
Could you please add the events of the next period?

See below for the details. The first one is better called "Lessons Learnt in DKG projects"

![grafik](https://user-images.githubusercontent.com/6708974/209356993-0342cdd9-6336-4883-9a81-427eb316e6fc.png)

Thanks,

Tobias

**Comment by pheyvaer** [comment]
Hi @kaefer3000 Are there urls for the events as well? Maybe a link where they can register?

**Comment by kaefer3000** [comment]
https://solid.ti.rw.fau.de/public/2023/solid-symposium/ for the last one in the list is the only one I am aware of.
